version: "3"

services: 
  mysql:
    image: mysql
    restart: always
    ports: 
      - 9090:3306
    volumes: 
      - ./mysql/data:/var/lib/mysql
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: 980525
  redis:
    image: redis
    ports:
      - 6379:6379
    restart: always
  
